checkpoint: checkpoints/video_best_dfew_uniform_pos_freq_best_uar.pth
data_dir: Datasets
val_split: test
stats_path: Datasets/DFEW/video_3dmm_stats_uniform.npz
data_type: dfew
sample_strategy: uniweform

num_classes: 7
model_type: large
temporal_module: transformer
hidden_dim: 512
head_dropout: 0.3
max_frames: 16
frame_step: 1
use_3dmm: true

batch_size: 1
num_workers: 4
amp: false

save_pdf: video_best_dfew_uniform_pos_freq.pdf
